version: '3'
services:
  eddi:
    build:
      context: .
      args:
        EDDI_VERSION: 4.8.4
        EDDI_ENV: production
        EDDI_MEMORY_MIN: 512m
        EDDI_MEMORY_MAX: 512m
    image: labsai/eddi:local
    environment:
      EDDI_VERSION: 4.9.1
      EDDI_JVM_OPTIONS: "-verbose:class -Xlog:gc*=debug:stdout:time,uptime,level -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/dumps/oom.bin -XX:+UseContainerSupport"
      EDDI_ENV: production
      EDDI_MEMORY_MIN: 512m
      EDDI_MEMORY_MAX: 512m
