version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo
    resource_class: large
    environment:
      MAVEN_OPTS: -Xmx6400m
    steps:
      ## Checkout the source code
      - checkout

      ## Restore any files that may have been cached from previous jobs
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Set permissions
          command: chmod +x mvnw

      - setup_remote_docker:
          version: 20.10.12

      - run:
          name: Run unit tests
          command: ./mvnw test

      - run:
          name: Build app & container
          command: ./mvnw package '-Dquarkus.container-image.build=true -Dquarkus.container-image.tag=5.0.0-b$CIRCLE_BUILD_NUM'

      ## cache the dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            chmod +x integration-tests.sh
            ./integration-tests.sh

      ## Push docker image if master build
#      - run:
#          name: Docker Push
#          command: |
#            if [ "${CIRCLE_BRANCH}" == "master" ]; then
#                echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
#                docker push labsai/eddi:5.0.0-b$CIRCLE_BUILD_NUM
#            fi

